import "@/styles/globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import clsx from "clsx";
import AppMainProvider from "@/providers/AppMainProvider";
import Nav from "@/components/nav";

const font = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          font.className,
          "bg-background dark:bg-background scroll-smooth"
        )}
      >
        <AppMainProvider>
          <main className="container-none md:container flex flex-col min-h-screen w-full mx-auto relative">
            <Nav />
            {children}
          </main>
        </AppMainProvider>
      </body>
    </html>
  );
}
