import "../styles/globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NextUIProviderWrapper from "@/providers/NextUIProviderWrapper";
import ToggleButtonProvider from "@/contexts/ToggleButton";
import Nav from "@/components/layouts/Nav";
import clsx from "clsx";

const font = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(font.className, " bg-slate-50 dark:bg-gray-900")}>
        <ToggleButtonProvider>
          <NextUIProviderWrapper>
            <main className="container flex flex-col min-h-screen w-full mx-auto relative">
              <Nav />
              {children}
            </main>
          </NextUIProviderWrapper>
        </ToggleButtonProvider>
      </body>
    </html>
  );
}
